[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.93"
askama = { version = "0.12.1", features = ["with-hyper"] }
askama_hyper = "0.1.0"
ctrlc = "^3.4.5"
http-body-util = "^0.1.2"
hyper = { version = "^1.5.0", features = ["http1", "server"] }
hyper-util = { version = "^0.1.10", features = ["tokio"] }
rimage = { version = "0.10.3", features = [
  "exif",
  "oxipng",
  "parallel",
  "quantization",
  "resizing",
  "avif",
  "jxl",
  "webp",
] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "^0.1.16", features = ["net"] }
