# .github/workflows/build.yml
name: Release binaries

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: install prerequisites
        run: sudo apt-get install -y libsystemd-sys
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOOLCHAIN_VERSION: nightly
        with:
          RUSTTARGET: x86_64-unknown-linux-gnu
          ARCHIVE_TYPES: tar.zstd
